# Generated by Django 5.1.7 on 2025-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='detalle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
