# Generated by Django 5.1.7 on 2025-05-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auditlog_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.planservicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.trabajador'),
            preserve_default=False,
        ),
    ]
