# Generated by Django 5.1.7 on 2025-05-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_cita_plan_cita_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='termino',
            field=models.TextField(blank=True, default=''),
        ),
    ]
