# Generated by Django 5.1.7 on 2025-05-22 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_cita_trabajador_alter_cita_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='boleta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
