# Generated by Django 5.1.7 on 2025-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_boleta_estado_pago_boleta_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
