# Generated by Django 5.1.7 on 2025-05-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cita'),
        ),
    ]
